version: '3'

services:
    mysql:
        container_name: chart-mysql
        image: mysql:5.7
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_USER: owner
            MYSQL_ROOT_PASSWORD: initpass  # テキトーなパスワード
            MYSQL_PASSWORD: initpass       # テキトーなパスワード
            MYSQL_DATABASE: chart-api-server
        volumes:
            - myinitdb:/docker-entrypoint-initdb.d
        command: >
            mysqld
                --character-set-server=utf8
                --collation-server=utf8_unicode_ci
                --skip-character-set-client-handshake
volumes:
    myinitdb: